# -*- coding: utf-8 -*-
"""researchaiagent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trpOejNIq5Q-UMnLOw7TiOhAYuX4CUGA
"""

!pip install -q langgraph langchain langchain-community langchain-groq duckduckgo-search

from google.colab import userdata
import os

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
print("Key loaded:", bool(os.environ.get("GROQ_API_KEY")))

from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_groq import ChatGroq


class AgentState(TypedDict):
    question: str
    search_results: str
    answer: str


def search_node(state: AgentState) -> AgentState:
    tool = DuckDuckGoSearchRun()
    try:
        state["search_results"] = tool.run(state["question"])
    except Exception as e:
        state["search_results"] = f"[Search failed: {e}]"
    return state


def summarize_node(state: AgentState) -> AgentState:
    llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)
    prompt = f"""Question: {state['question']}
Search results: {state['search_results']}

Write a clear, concise answer using only the information above.
If the results don't contain enough info, say so honestly."""
    try:
        state["answer"] = llm.invoke(prompt).content
    except Exception as e:
        state["answer"] = f"[Summarization failed: {e}]"
    return state


graph = StateGraph(AgentState)
graph.add_node("search", search_node)
graph.add_node("summarize", summarize_node)
graph.set_entry_point("search")
graph.add_edge("search", "summarize")
graph.add_edge("summarize", END)
research_agent = graph.compile()

print("Agent built successfully.")

!pip install -q ddgs

result = research_agent.invoke({
    "question": "What is the current version of Python?",
    "search_results": "",
    "answer": ""
})

print("QUESTION:", result["question"])
print("\nANSWER:\n", result["answer"])